### ISSUE TITLE
compilation error in nim-smie.el

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#100] opened 2016-03-23 12:41 UTC
I try to get this package working, and I got compilation errors.

    Compiling file /home/arne/.emacs.d/elpa/nim-mode-20160322.1502/nim-smie.el at Wed Mar 23 13:33:42 2016
    nim-smie.el:114:1:Error: Symbol's value as variable is void: internal--listify

I should mention, I am completely new to emacs, I just want to try out how well editing nim from emacs is.

**Comment by yuutayamada** [comment] 2016-03-23 14:51
Did you install nim-mode via MELPA?
There are some dependencies in this package and you may need
[this setting](https://melpa.org/#/getting-started) to use MELPA.

What emacs version are you using?
(This package needs emacs 24.4 or later version)

How did you compile? (there some ways to compile emacs files and
it could be path setting error if you don't specify `-L .` option)

**Comment by yuutayamada** [comment] 2016-03-23 15:17
just FYI, https://github.com/syl20bnr/spacemacs is popular starterkit for Emacs.
If you favor modal editing like vim, spacemacs defaults almost vim keybind and
includes many cool plugins of Emacs (, but you can choose emacs keybinding as well)

**Comment by yuutayamada** [comment] 2016-03-23 19:01
I saw you are using emacs24.5 later on irc.
In that case, I guess it's byte compile trouble.
(because nim-helper.el has that `internal--listify`)

Could you delete all the XXX.elc files in your nim-mode directory?
and then try open up emacs again?
Those .elc are called byte-compiled files. It speed up to load library, but
sometimes it holds old data.

**Comment by krux02** [comment] 2016-03-24 00:28
Thanks for the hint to spacemacs, I used vim in the past for a c++ project where I installed YouCompleteMe, and I really liked the completion engine. I also managed to configure my vim configuration and my own button mapping and after half a year of full time vim, I can only say, I hate modal editing. So I am happy to try out emacs and so far I think emacs is a much friendlier first time experience than vim, and I try out how good the default button mapping of emacs is.

Back to topic, I still have no idea how to test weather everything works as it is supposed to work. The only way to find out if the packe works that I know at the moment is by redoing the installation process with M-x list-packages search for nim-mode click on it with the mouse, and repress the install button there. There has to be a better way. 

There are also a lot of dependencies that I found out on my own and installed. I think they should be mentioned in the readme.

So far I do have syntax highlighting, but I do not have completion, but it might be because I just don't know how to enable it, I think I have to read a bit further to understand how completion in emacs works.

**Comment by yuutayamada** [comment] 2016-03-24 03:25
Probably readme.md helps you to enable auto-complete?
(Note that company-mode is COMP(lete) ANY-mode)

The key point is to set path of nimsuggest.
It affects most features of nim-mode:
- jump to definition
- auto-completion
- syntax check (if you use flycheck-nim-async.el)
- popup type information in minibufffer under the cursor

> There are also a lot of dependencies that I found out on my own and installed. I think they should be mentioned in the readme.

I just curious, did you use MELPA to install?
There is package dependencies information at nim-mode.el, so if you couldn't 
install something correctly, it may a bug(or bugs?)

**Comment by krux02** [comment] 2016-03-24 03:59
Since it is basically the first thing that is written in the readme, yes I used melpa to install this plugin. Honestly I don't even know if there is an alternative way to do so.

**Comment by krux02** [comment] 2016-03-24 05:40
I just added the line from the readme to my .emacs:

    (add-to-list 'company-backends
               '(company-nim :with company-nim-builtin))

this is what I get:

    Warning (initialization): An error occurred while loading `/home/arne/.emacs':
    Symbol's value as variable is void: company-backends

Not very helpful at all in finding out what the problem might be.
By the way, these are the installed packages:

      color-theme
      color-theme-sol... 
      commenter          
      company            
      concurrent         
      ctable             
      dash               
      deferred         
      epc                
      epl               
      flycheck         
      flycheck-nim
      let-alist        
      markdown-modetext
      nim-mode          
      pkg-info           
      seq                
      solarized-theme
      subr+

If I am missing something fundamentally, please tell me. Btw I think, that subr+ should be listed as a package dependency, because without it, this packe will not built.

**Comment by yuutayamada** [comment] 2016-03-24 06:54
> Not very helpful at all in finding out what the problem might be.

In emacs basically you need major-mode specific hook like:
```lisp
(add-hook 'nim-mode-hook
          '(lambda ()
              ;; write here nim-mode specific configuration
              (add-to-list 'company-backends
               '(company-nim :with company-nim-builtin))
           ))
```
there are another ways to configure, but this is most basic (I think)

> If I am missing something fundamentally, please tell me. Btw I think, that subr+ should be listed as a package dependency, because without it, this packe will not built.

[flycheck-pos-tip](https://github.com/flycheck/flycheck-pos-tip) or [flycheck-tip](https://github.com/yuutayamada/flycheck-tip) may good for you?

About subr+. I have no idea why we need that repository because there is
no function that depends subr+. (but `if-let` function depends subr.el of emacs25.1)
In this repository, we are checking builds of some emacs versions: 24.4, 24.5, and snapshot.
So, I hope it's your misunderstanding...

**Comment by yuutayamada** [comment] 2016-03-24 16:11
Sorry @krux02, I might missing one thing.
You need activate `company-mode` before you use related variables
 (i.e company-backends)

To do so, you can add the variable like this:

```lisp
;; see also http://company-mode.github.io/
(add-hook 'after-init-hook 'global-company-mode)
```

maybe we should add a link of company-mode to the readme

**Comment by yuutayamada** [comment] 2016-03-25 07:28
I'm just putting my nim-mode configuration here, so people might get hints (I hope)
[init_nim-mode.el](https://github.com/yuutayamada/emacs.d/blob/master/.emacs/pkg_conf/init_nim-mode.el)

**Comment by krux02** [comment] 2016-04-06 11:32
I would really appreciate if there would be a test, that nim-mode can be installed on a fresh emacs without conflicts. So dependencies like `flycheck-nim` `subr+` `company` should be in the dependencies list. It just gives this mode a smoother start.

**Comment by yuutayamada** [comment] 2016-04-15 22:39
I closing this issue because I made sure installing nim-mode from MELPA in emacs 25
(PR #100 fixed this issue)

**Comment by yuutayamada** [comment] 2016-07-25 19:27
I'm re-opening this issue because of #131

@krux02 Can you try `make test` command in this repository?
It installs dependent packages and tests compilation, indentation and syntax highlight. (the files are saved .cask directory in this repo and you can safely delete after the test) and you may need to change EMACS variable to the emacs version you failed to install. (emacs24 or something)

If it succeed the result should be similar to this: https://travis-ci.org/nim-lang/nim-mode/jobs/147246187

**Comment by krux02** [comment] 2016-07-25 21:13
Ok, I did what you said. I removed my version of emacs-git that I build from source, and reinstalled the version that is bundled with the package manager, and then I did clone this repository, did make test. Error cask not known. Search for cask install it. `make test` again, and it works, no problems.

Then I moved `.emacs.d` to `.emacs.d.backup` to make sure the config is empty. Then I add to this new repository the melpa sources, and I install from there nim-mode, and to my surprise it works to install, no problem. But I don't stop here. When I first installed nim-mode from melpa I did not have an environment with cask installed, maybe that was the reason, so I removed cask, cleaned the `.emacs.d`, and did a reinstall of nim-mode, and it still worked. So now I just have to guess, that I had some old remains of nim-mode in my old `.emacs.d` that I don't have anymore at this point in time, that caused the problem. But on a clean emacs the installation works. Ok installation is one thing, let's see if it also works. Here is a screenshot:

![screenshot](http://i.imgur.com/cg5nxiT.png)

* completion ✔
* flycheck ✔
* syntax highlighting ✘

**Comment by yuutayamada** [comment] 2016-07-25 22:05
I think you have needless configuration, which I suggested to check nim-mode's freezing problem. (otherwise your situation doesn't make sense because we have syntax check tests as well)

What's happen if you don't use your configuration? (you used your configuration to activate company-mode. right?)

**Comment by krux02** [comment] 2016-07-25 23:26
without my config, I don't have company and the colors are black letters on white background. I also have to manually active nim-mode company-mode and flycheck. But even then I don't get proper nim completion.

**Comment by yuutayamada** [comment] 2016-07-25 23:48
> I also have to manually active nim-mode company-mode and flycheck. But even then I don't get proper nim completion.

Sorry, currently nim-mode doesn't include company-mode setting for nim. So still highlight doesn't work when you activate nim-mode?

**Comment by krux02** [comment] 2016-07-26 00:10
completely right, highlighting doesn't appear when I activate `nim-mode`

**Comment by yuutayamada** [comment] 2016-07-26 00:59
I have no idea what's going on your Emacs... Can you check this?:

```sh
# in nim-mode repository
$ nim e ./starterKit.nims
```

this opens a new Emacs with clean state (basically it's same state as cask's test)
Is this Emacs highlight correctly?

**Comment by krux02** [comment] 2016-07-26 01:49
![emacs](http://i.imgur.com/gB8AIaA.png)

* `M-x nim-mode` doesn't work [no match]
* `M-x package-list-packages` tells me `nim-mode` is installed

**Comment by yuutayamada** [comment] 2016-07-26 02:15
Sorry, I think I can't help your situation because I can't reproduce. Hope someone point out your cause of trouble.

**Comment by yuutayamada** [comment] 2016-07-26 02:22
I hoped the `nim e starterKit.nims` show you syntax highlihgt on scratch buffer like this:
![screenshot from 2016-07-25 19-11-01](https://cloud.githubusercontent.com/assets/1082473/17124006/d000aa76-529c-11e6-9598-32fca3009384.png)

if it highlight correctly, then there is something in your configuration. (I guessed byte-compiled *.elc files, which often cause troubles, but sorry I couldn't prove it)

**Comment by yuutayamada** [comment] 2016-07-26 02:26
cask is another package manager for Emacs. We use it for testing, but the dependent packages are same as MELPA. You can delete .cask directory if you don't check anymore.

**Comment by krux02** [comment] 2016-07-26 12:09
Today I tried out `nim e starterKit.nims`, because I did not test the scratch buffer. Apparently `nim e starterKit.nims` does not work, when I don't update my path with: `export PATH="/home/arne/.cask/bin:$PATH"` but that's ok. Now the question is, maybe some `*.elc` files on your system cause that it works on your computer, but not on any other computer. So my question is, did you test the installation on a computer you do not use to develop on, or at least a fresh virtual machine? I remember that at the time when I was a tutor for a c++ programming course the professor gave out his adapted version of codelite, and he tested the installation on his system, and it worked. One student from 100 came to me and asked me why she couldn't install the software on her windows machine. I couldn't help her and I contacted the professor with it. He showed me that the installation went completely smooth on his computer after completely removing it, and that it has to be her machine that was causing the problem. After all, the professor had something in the registry that was not deleted, and caused the installation to work on his system, and only his system. The installation worked on nobody's computer, the other 100 students were just afraid to ask, because they did not want to feel stupid, and just worked only on university computers where the software was already installed.

So please test at least on a virtual machine.

**Comment by krux02** [comment] 2016-07-26 13:44
By the way `nim e starterKit.nims` starts with an empty scratch buffer.

**Comment by yuutayamada** [comment] 2016-07-26 15:01
Please forget about starterKit.nims, I hoped you could easy to debug
if it was nim instead of emacs lisp. But seems I need to change the
script to get work.

I summarized our situation

- on your Arch
  - Emacs 25 is working fine
  - Emacs 24.5 check `make test` -- tests are passed
  - This one I don't much understand how you did check:
    On Emacs 24.5 you checked nim-mode without your config and
    highlight doesn't work
  
- I checked ubuntu 16.04 LTS
  - I'm using Emacs master branch and highlight is ok
  - installed emacs24.5 via apt-get
    I renamed master branch's emacs to emacs-tmp to prevent to be used from test
  - test is ok (make test command)

- on travis
  - we are checking emacs 24.4, 24.5 on travis (syntax highlight, indentation)


My thought:
- if the problem is Arch specific, why it only happens in emacs 24.5? (not 25)
- if the problem is emacs version specific, why travis's tests are passed?
- you tested `make test` Emacs 24.5 on Arch and result was ok, this means
  you can use nim-mode with highlight on Emacs 24.5 if you configure
  nim-mode correctly or current tests are broken.

I'm really confusing what you should do next to fix your problem. Maybe I should try arch, but currently my motivation is too law.

**Comment by krux02** [comment] 2016-07-26 15:41
If you do try arch, installation is horrible (it's like getting emacs working :wink: ). Use [Manjaro](https://manjaro.github.io/) instead. People I know who use it say it is as easy as ubuntu to install.

**Comment by yuutayamada** [comment] 2016-07-26 15:53
Haha. thank you for your advice, but I would rather fix #108 (nim-mode
freeze in big files) by introducing nimsuggest's highlight than trying
to arch :)

**Comment by krux02** [comment] 2016-07-26 16:30
Are you sure, that your emacs 24 does not accidently use some files from emacs 25? Most files are separated by version in `/usr/share/emacs/24.5` But you never know what actually happens under the covers.

I made sure that this does not happen, by completely removing the `emacs-git` package from my system. So can you test it on a system that does not have emacs from the master branch installed?

**Comment by krux02** [comment] 2016-07-26 18:58
I installed emacs 25 again (compilation takes 45 minutes) and tested `nim e starterKit.nims` with it. It complains about that it can't find `let-alist`, and the scratch buffer is empty. But with this version the syntax highlighting works again.

**Comment by yuutayamada** [comment] 2016-07-26 20:06
@krux02 I could reproduce in Emacs 24.5 ubuntu and I didn't open emacs manually. I thought `make test` command was enough, but it's not... (and still tests are passed)

**Comment by krux02** [comment] 2016-07-26 20:50
I would be interested what you needed to do to reproduce this behavior.

**Comment by yuutayamada** [comment] 2016-07-26 21:15
> I would be interested what you needed to do to reproduce this behavior.

- Open up emacs with: `emacs24 -Q`
- Paste below code to scratch buffer and type C-x C-e at end of close parenthesis

```lisp   
(defconst package-archives
  '(("melpa" . "https://melpa.org/packages/")
    ("ELPA"  . "https://tromey.com/elpa/")
    ("gnu"   . "https://elpa.gnu.org/packages/")))
```

- M-x package-list-packages and install nim-mode.
- C-x C-f foo.nim return
- Type something and noticed the highlight was nothing

just to be sure I deleted my emacs repository as you said, though I don't use `make install` to use master branch. I didn't check manually because syntax tests were ok...

**Comment by yuutayamada** [comment] 2016-07-27 16:49
@krux02 I made sure that #133 fixed that highlight errors on Ubuntu. Hope it fixes on arch too. (note you may need to move your .emacs.d to make sure, otherwise emacs might use old nim-mode. I don't use .emacs.d as my personal configuration, so I forgot to write above instruction to make sure)

**Comment by krux02** [comment] 2016-07-27 17:12
ok, now it works, I guess you can close this now.

**Closed** 2016-07-27 17:27 UTC
