### ISSUE TITLE
`nim-mode` is unusable in bigger files

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#108] opened 2016-04-08 17:34 UTC
The nim-mode constantly blocks any input on a bigger file like this [opengl.nim](https://github.com/nim-lang/opengl/blob/master/src/opengl.nim). This issue still remains, when I disable `company` and `flycheck`.

All I notice, is that the edior freezes whenever I scroll around, and while the editor is frozen, one processor is on 100% cpu usage.

**Comment by yuutayamada** [comment] 2016-04-08 18:14
Can you reproduce it with emacs -Q option? (I mean minimal setting for nim-mode, not including
your personal configuration)
turning off company and flycheck isn't enough to check whether it's because of 
nimsuggest related thing of not.

and can you move *message* buffer?
your emacs might emit something related error message.

**Comment by yuutayamada** [comment] 2016-04-08 18:29
@krux02 never mind. I made sure the problem.

**Comment by yuutayamada** [comment] 2016-04-08 18:39
the cause of the freeze is highlighting of emacs

I commented out font lock part in nim-mode.el
```lisp
  ;; ;; Font lock
  ;; (setq-local font-lock-defaults
  ;;             `(,(append nim-font-lock-keywords
  ;;                        nim-font-lock-keywords-extra
  ;;                        nim-font-lock-keywords-2
  ;;                        nim-font-lock-keywords-3)
  ;;               nil nil nil nil
  ;;               (font-lock-syntactic-face-function
  ;;                . nim-font-lock-syntactic-face-function)))
```
then the freeze was stopped after reboot emacs.

maybe using nimsuggest's syntax highlight solves this problem, 
but I don't have time to do now.

**Comment by krux02** [comment] 2016-04-12 22:00
I wouldn't say it'

**Comment by krux02** [comment] 2016-04-12 22:02
I don't think, that `enhancement` is the right tag here, because for people who need to work with bigger files regularly, this is a showstopper.

**Comment by yuutayamada** [comment] 2016-04-12 22:55
@krux02 Can you update nim-mode?
Some improvements were merged related to nimsuggest.
I think it might solve (or reduce) your problem.

My understanding of your original problem is you didn't turn off el-doc feature, 
which uses nimsuggest feature when you move cursor.

**Comment by yuutayamada** [comment] 2016-04-12 23:08
@krux02 how long did your machine freeze?
(for me, it was 0.5 sec when I move page move in opengl.nim file with latest nim-mode)

**Comment by krux02** [comment] 2016-04-13 02:23
Ok I made sure to have the newest nim-mode, and the freeze is still there. It freeze is very inconsistent in time, sometimes more than 10 seconds, and sometimes less than 0.5 seconds. And no I did not turn down el-doc feature, until now I had never heared from it. My current solution for this problem is, whenever I need to take a look at this file, I use another editor.

**Comment by yuutayamada** [comment] 2016-04-18 00:22
@krux02 I fixed #111, so please update nim-mode.

and I want you to distinguish your problem whether it's related to
nimsuggest features (flycheck, company-mode, el-doc, or
nim-thing-at-point) or syntax highlight problem

To do so, please set following configuration in your emacs config
file before you configure nim-mode stuff:

```lisp
;; (1) this configuration will stop all nimsuggest related functions
(defconst nim-nimsuggest-path nil)

;; (2) this configuration will disable all syntax highlight for nim-mode
(add-hook 'nim-mode-init-hook
          (lambda ()
            (defconst nim-font-lock-keywords nil)
            (defconst nim-font-lock-keywords-2 nil)
            (defconst nim-font-lock-keywords-3 nil)
            (defconst nim-font-lock-keywords-extra nil)))
```

You may need to reboot your emacs to make sure the difference.

If the freeze is stopped in this configuration, please comment out one of them
(I mean (1) or (2)) and let me know which is your problem.

**Comment by krux02** [comment] 2016-04-18 01:30
It's definitively (2) that makes the difference. Disabling or enabling the nimsuggest has no noticeable affect on the performance.

**Comment by LemonBoy** [comment] 2016-05-30 12:44
In big-ish files the `post-self-insert-hook` functions slow down emacs to a crawl when typing, I guess something could be done about this ?

**Comment by timmyjose** [comment] 2016-09-27 16:37
I have the same issue with nim-mode. Even on small files, I can see a visible lag, especially after the "#" character when writing out comments. This is very bizarre. I don't really think it is usable at all. Looks like uninstalling it is the way to go (after reading the comments in this thread).

**Comment by yuutayamada** [comment] 2016-09-27 16:56
@timmyjose I don't have the lag issue in 3000 LOC (system.nim) and when I made
sure this problem, it was clearly syntax highlight problem with big files. So please make new issue if you have lag issue with small files.

And describe:
- nim's and nimsuggest versions (or git hash)
- error messages on *Message* buffer if available
- try not using nimsuggest

**Comment by yuutayamada** [comment] 2016-09-27 18:21
I'm closing this issue because I made #139 to reduce needless information.

**Closed by yuutayamada** 2016-09-27 18:21 UTC
Labels: enhancement, syntax highlighting
