### ISSUE TITLE
Nim-mode not found in MELPA

### ISSUE THREAD

**Issue by DrMoriarty** [nim-lang/nim-mode#196] opened 2018-06-25 08:26 UTC
Conforming Bugs
===============

Please tell us below:

- [x ] basic information
   - OS name
Macosx 10.13.4
   - Versions: Emacs, Nim compiler, and nimsuggest
Emacs 25.1.1
Nim Compiler Version 0.18.0 [MacOSX: amd64]
I don't know nimsuggest version, but I installed it today by nim
- [x ] Are you using latest version of nim-mode?
I don't know
- [ x] Are there message related to nim-mode in `*Messages*` buffer?
yes
- [x ] Did you read README.md?
yes
- [ ] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc)
   - [ ] Did you try nim-mode without nimsugggest-mode? What happened?
         (Comment out nimsuggest-mode's config please)

And describe your problem:

When I try to install nim-mode to emacs (`package-install nim-mode`)
it shows me an error `https://melpa.org/packages/nim-mode-20180212.1040.tar: Not found`
*Messages* buffer contains this:
```
  16|Contacting host: melpa.org:443                                                                                                                                         
  17|Opening TLS connection to ‘melpa.org’...
  18|Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org’...failed
  19|Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 melpa.org --protocols ssl3’...failed
  20|Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...done
  21|Opening TLS connection to ‘melpa.org’...done
  22|package-install-from-archive: https://melpa.org/packages/nim-mode-20180212.1040.tar: Not found
```

**Comment by krux02** [comment] 2019-05-03 21:35
is this still a problem? As I can't reproduce the problem right now. I don't have a problem to install the package.

**Comment by krux02** [comment] 2019-05-05 22:58
Since I cannot reproduce this problem, and this issue is quite old by now, I close it for now. If you can verify that the problem still exists, I will try to reproduce it and reopen.

**Closed by krux02** 2019-05-05 22:58 UTC
