### ISSUE TITLE
Turn off automatic indentation when I have manually dedented beforehand?

### ISSUE THREAD

**Issue by endrebak** [nim-lang/nim-mode#54] opened 2015-08-10 15:04 UTC
If I have the following code 

```nim
type
  TRange = object
    low: int
    high: int

iterator items(range: TRange): int =
  var i = range.low
  while i <= range.high:
    yield i
    inc i

iterator pairs(range: TRange): tuple[a: int, b: char] =
  for i in range:
    yield (i, char(i + ord('a')))
```

and enter the following line at the bottom and press enter

```
for i, c in TRange(low: 1, high: 3):
```

I get the indentation:

```
    for i, c in TRange(low: 1, high: 3):
```

which makes some sense, as it is on the same position as the yield above.

But since I chose to start my line at column 0 I find it annoying that it automatically jumps out to 4 (If I had wanted to continue on column 4 I would not have dedented my line). Is there a way to turn this behavior of automatic indentation after manual dedentation off? After having used the Python mode for so long it almost feels like a bug.

**Comment by endrebak** [comment] 2015-08-10 15:07
I am using the nim-mode from https://github.com/syl20bnr/spacemacs/tree/develop/contrib/!lang/nim but I doubt it should matter.

**Comment by yuutayamada** [comment] 2015-08-11 07:36
It seems like #19.(and solved now) I'm not sure this is related or not, but MELPA's repository URL was
@reactormonk's. So if spacemacs was downloading from MEAPA, that might be the cause. 

Today I sent a PR to MELPA about the repository URL, so you can update later. (probably 1 day or 2 days later?)

**Comment by endrebak** [comment] 2015-08-11 08:35
Will do, thanks for your kind reply.

**Comment by yuutayamada** [comment] 2016-02-03 03:05
@endrebak I made sure spacemacs community and I seem now the indentation of enter key
is working. [see also](https://github.com/syl20bnr/spacemacs/issues/4403)
I'll close this issue, but if you still have problem, feel free to re-open or make new issue.

**Closed by yuutayamada** 2016-02-03 03:05 UTC
