### ISSUE TITLE
typing `block:` unindents the current line

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#102] opened 2016-03-31 20:03 UTC
Typing `block:` unindents the current line, but this is not what is supposed to happen. Apparently the `:` at the end of the line triggers the undindentation. For some reason, in the next indented line after `block:` this phenomenon does not happen.

**Comment by yuutayamada** [comment] 2016-03-31 21:10
Could you give me minimal reproducible code?
I'm still not sure what you are trying to say.
(Sorry, I'm not native English speaker)

**Comment by krux02** [comment] 2016-03-31 21:22
let's say, this is the current line: `  block`, and the write cursor is at the end of the line. Now I write a `:`, and the line instantly becomes `block:`. One indentation level is removed.

**Comment by yuutayamada** [comment] 2016-03-31 21:29
```nim
when true:
  block: #<- you type ":"
```
then become?
```nim
when true:
block:
```
hmm, I couldn't reproduce it...

**Comment by yuutayamada** [comment] 2016-03-31 21:40
Historically nim-mode inherited many functions from
python-mode.el and the ":" has `nim-indent-electric-colon` elisp
function. I guess it's somehow affected your environment... (not
sure really, but) You might avoid the function by following config:

```lisp
;; Add this in your common-setup function for nim-mode
(define-key nim-mode-map ":" nil)
```

**Comment by krux02** [comment] 2016-03-31 22:38
```
when true:

  block: #<- you type ":"
```

becomes this:
```
when true:

block:
```
yes indeed it has strange behavior

**Comment by yuutayamada** [comment] 2016-07-19 20:13
I'm closing this issue because in recent nim-mode, the colon behavior changed.

And now you can turn off completely by:
```lisp
(add-hook 'nim-mode-hook (lambda () (electric-indent-mode -1)))
```

**Closed by yuutayamada** 2016-07-19 20:13 UTC
Labels: bug, feedbackWelcome
